# Server Configuration
server:
  port: 8080

  tomcat:
    max-threads: 200
  compression:
    enabled: true

spring:
  mvc:
    favicon:
      enabled: false


endpoints:
  enabled: false
  info:
    enabled: true
  health:
    enabled: true


# Eureka Configuration
eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
    status-page-url-path: ${server.contextPath:}/info
    health-check-url-path: ${server.contextPath:}/health
  ## Disabled by default
  client:
    register-with-eureka: false
    enabled: false

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 90000

ribbon:
  ConnectTimeout: 20000
  ReadTimeout: 60000
  MaxTotalHttpConnections: 200
  MaxHttpConnectionsPerHost: 100

# Zuul Routes Configuration
zuul:
#  trace-request-body: true
  sensitiveHeaders: Cookie,Set-Cookie
  SendErrorFilter:
    post:
      disable: true
  ignored-services: registry
  routes:
# ROUTE EPAM STUFF EXPLICITLY
    api:
          path: /api/v1/**
          serviceId: api
          stripPrefix: false
    uat:
          path: /uat/**
          serviceId: uat
          sensitiveHeaders:

    # ROUTE EPAM STUFF EXPLICITLY
    ui_icons:
          path: /epam/**
          serviceId: uat
          stripPrefix: false

## Consul as service registry
---
spring:
  profiles: eureka
  cloud:
    consul:
      enabled: false
      discovery:
        register: false
eureka:
  client:
    register-with-eureka: true
    enabled: true
## Consul as service registry
---
spring:
  profiles: consul
  cloud:
    consul:
      enabled: true
      discovery:
        register: true
eureka:
  client:
    register-with-eureka: false
    enabled: false
---
